"""create initial application tables

Revision ID: 1aa0f0e197a3
Revises: 89185b9f8558
Create Date: 2026-09-04 16:16:05.227257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa0f0e197a3'
down_revision: Union[str, Sequence[str], None] = '89185b9f8558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('udyam_number', sa.String(length=50), nullable=True),
    sa.Column('cin', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidders_cin'), 'bidders', ['cin'], unique=False)
    op.create_index(op.f('ix_bidders_gstin'), 'bidders', ['gstin'], unique=False)
    op.create_index(op.f('ix_bidders_pan'), 'bidders', ['pan'], unique=False)
    op.create_index(op.f('ix_bidders_udyam_number'), 'bidders', ['udyam_number'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_bids_bidder_id'), 'tender_bids', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_tender_bids_tender_id'), 'tender_bids', ['tender_id'], unique=False)
    op.create_table('bid_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['tender_bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_documents_bid_id'), 'bid_documents', ['bid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_documents_bid_id'), table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_index(op.f('ix_tender_bids_tender_id'), table_name='tender_bids')
    op.drop_index(op.f('ix_tender_bids_bidder_id'), table_name='tender_bids')
    op.drop_table('tender_bids')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_bidders_udyam_number'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_pan'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_gstin'), table_name='bidders')
    op.drop_index(op.f('ix_bidders_cin'), table_name='bidders')
    op.drop_table('bidders')
    # ### end Alembic commands ###
